# Generated by Django 2.1.4 on 2018-12-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaCreacion', models.DateField()),
                ('nivel', models.IntegerField(default=0)),
            ],
        ),
    ]
